### ISSUE TITLE
SimplexNoise

### ISSUE THREAD

**Issue by thinium** [blakelymcconnell/m4l_js2liveAPI#1]
Hi blakely, in your global_m4l.js you are accessing the Perlin noise function under gp.SimplexNoise(). Could you please give me some hints about how gp is constructed and how you refer to other javascript files in max for live? I thought it's impossible to import external javascript files but it looks to me that your "global_m4l.js" knows about SimplexNoise, which is not defined in the file. Many thanks!

**Comment by blakemcconnell** [comment]
hi ukelady, I have a m4l patch that contains a js object my global m4l js file, and another js object for the global perlin noise js file.  both js files can be "seen" throughout the live set--the trick (hack) is to send a "compile" message to the global_m4l js, and then to all your other js objects, every time you load the set, or make changes to your files.  it's frustrating, but rewarding once you get it all working.  

as for an example of implementation:

this.outlets = 2;

var api = new LiveAPI("live_set");
var tempo = api.get("tempo");
t_test = new g.Transport(tempo);
var easing = new g.Easing(1000, 30);
var sv = 0;
var ev = 0;
var pev = 0;
var drunk_max = new g.Drunk(60, 80);
var drunk_min = new g.Drunk(10,20);
var counter = 0;

function bang() {
    if (t_test.bar_bang(api.call("get_current_beats_song_time"))) {
        outlet(0, "bar");
    }
    else if (t_test.beat_bang(api.call("get_current_beats_song_time"))) {
        outlet(0, "beat");
    }
    outlet(1, Math.floor(easing.move(easing.easeInOut(easing.counter/easing.duration, sv, ev), ev)));
}

function anything() {
    var a = arrayfromargs(messagename, arguments);

```
if (a[0] == "move") {
    drunkstep();
}

if (a[0] == "rate") {
    easing.set_rate(a[1]);
    post(easing.rate, "\n");
}

if (a[0] == "test") {
    var test = new gp.SimplexNoise();
    post(Math.floor(test.noise(1.,1.)), "\n");
}
```

}

function drunkstep() {
    if (counter === 0) {
        sv = easing.set_start_val(10);
        ev = easing.set_end_val(100);
        pev = ev;
        //post("1", "\n");
    }
    else if (counter % 2 != 0) {
        sv = pev;
        ev = ev = drunk_min.step(1,3);
        pev = ev;
        //post("2", "\n");
    }
    else {
        sv = pev;
        ev = ev = drunk_max.step(1,3);
        pev = ev;
        //post("3", "\n");
    }
    easing.start_motion();
    counter ++;
    //post("counter " + counter, "\n");
}

hope this helps!

**Comment by thinium** [comment]
Yes that definitely helps. Thanks for the explanation!
